name: scrap_dart
description: A simple command-line Web Scrapper.
version: 1.1.0
homepage: https://github.com/nurseiit/scrap_dart
author: Nurseiit Abdimomyn <nurs@unist.ac.kr>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
  html: ^0.14.0+2
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
